responder_pergunta_consumidor:
  description: >
    Responda questões relacionadas ao Código de Defesa do Consumidor (CDC) brasileiro.
    Forneça orientação clara sobre direitos do consumidor, responsabilidades do fornecedor,
    práticas comerciais e mecanismos de defesa disponíveis.

    **Pergunta:**
    {question}

  expected_output: >
    Uma resposta precisa e bem estruturada baseada no Código de Defesa do Consumidor
    e regulamentações relacionadas. Quando aplicável, cite os artigos específicos do CDC
    e forneça orientações práticas sobre como proceder.
    
  agent: especialista_defesa_consumidor